# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a50tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.cache/wt [current_project]
set_property parent.project_path C:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.srcs/sources_1/new/pole.v
  C:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.srcs/sources_1/new/zero.v
  C:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.srcs/sources_1/new/DirectIIR_liuqi.v
}
read_ip -quiet c:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property is_locked true [get_files c:/Users/GodWa/Desktop/DirectIIR_liuqi/DirectIIR_liuqi.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top DirectIIR_liuqi -part xc7a50tcsg324-1


write_checkpoint -force -noxdef DirectIIR_liuqi.dcp

catch { report_utilization -file DirectIIR_liuqi_utilization_synth.rpt -pb DirectIIR_liuqi_utilization_synth.pb }
